---
- name: Allow Test port 222
  hosts: linuxTest
  tasks:
    - iptables:
       chain: INPUT
       protocol: tcp
       destination_port: 222
       jump: ACCEPT
       comment: Allow test tcp port 22
